language: go
go:
- 1.x
deploy:
  provider: s3
  access_key_id: AKIAJICWI7L5UYEYIK7Q
  secret_access_key:
    secure: qlrFGtIN7JoWN0GBFYZN8p2FNqgtN0iYSA2lWHuv3Ajr1RUnnEWtgxF+T8CGqjWPOc2O6Ho7YCGH1X/bvnHYq3q5V51Z6Tz3h97ZhVLk7yMmUoIaJJDaUiygio6Z7kUf3MMCmQLkXs69ECHsLfNqbDPFT357EcGCskWWBc0skDTtLIPtjcOjKp3qzwRk8Ep2cQYY8ATGVPFG23qI2h3ubcsCv/fviN+qQWiOamVAEAIc/5ZyzkfUavGupjnuzWADDhKxqvNyOCNHBCdX1b3tPV8uSBm4vlnAGn2xVVIu8EF/asqdSk5ZBRyjnZTATViRaVOz7OTsHsaealE9EEpsUpElKmTIzW8PiO3HqVUTFHJYlBBlpkg09dvgWN1nY7s8tG3U+LCFaCBMyzikwhvQcivAgP1RGgom94PX4gm3rO0BdvLHkZnSLEKr946/SNDZvG+MEraFvlqvlbFyq2jltFLWGKQ7xbJb1KUexnBfOYEw04fFgHCmqc+I7Us73ShNO6r9WkG9SNXT7/m9YSKv5lugoQiUiFvV9RYyFExkhzeuIuru3NrCHIAMgNNA0IRjc25f3voF6oqaWJurt5ljjOT36Rdmq1CPsmAnlRtK6IE+LACKj9cJ34gZIo6odRbdiJP0YoXS82q6e8jSdO5djBVVfyl5XpkDRpOor2q/mM8=
  bucket: unomaly
  upload-dir: releases/aws
  local_dir: cloudwatch
  acl: public_read
  on:
    repo: unomaly/aws-ingestion
